# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YcKxS5p6ra3tNHPe6Oc3IZt47X4gaac
"""

!pip install openmeteo-requests requests-cache retry-requests

import openmeteo_requests
import requests_cache
import pandas as pd
from retry_requests import retry
from sklearn.ensemble import RandomForestRegressor

# 1. جلب البيانات من الإنترنت مباشرة إلى السحابة
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

url = "https://api.open-meteo.com/v1/forecast"
params = {
    "latitude": 25.5324,
    "longitude": 37.0592,
    "daily": ["temperature_2m_max", "temperature_2m_min", "et0_fao_evapotranspiration", "wind_speed_10m_max", "shortwave_radiation_sum"],
    "wind_speed_unit": "ms",
}
responses = openmeteo.weather_api(url, params = params)
daily = responses[0].Daily()

# 2. ترتيب البيانات في جدول (بدون الحاجة لحفظها في ملف)
daily_data = {
    "temperature_max": daily.Variables(0).ValuesAsNumpy(),
    "temperature_min": daily.Variables(1).ValuesAsNumpy(),
    "wind_speed_max": daily.Variables(3).ValuesAsNumpy(),
    "solar_radiation": daily.Variables(4).ValuesAsNumpy(),
    "et0": daily.Variables(2).ValuesAsNumpy()
}
df = pd.DataFrame(data = daily_data)
print("تم جلب البيانات بنجاح من الإنترنت مباشرة إلى السحابة! ☁️")

# 3. تدريب الذكاء الاصطناعي
X = df[['temperature_max', 'temperature_min', 'wind_speed_max', 'solar_radiation']]
y = df['et0']

model = RandomForestRegressor(random_state=42)
model.fit(X, y)
print("تم تدريب الذكاء الاصطناعي بنجاح! 🧠✅")

# 4. التنبؤ بيوم جديد (حرارة 40، صغرى 28، رياح 6، إشعاع 24)
new_day_weather = [[40.0, 28.0, 6.0, 24.0]]
predicted_et0 = model.predict(new_day_weather)

print("\n=== نتيجة الاختبار ===")
print(f"توقع الذكاء الاصطناعي لقيمة ET0 لهذا اليوم هو: {predicted_et0[0]:.2f} ملم/يوم")